import sqlite3 from 'sqlite3';
import { open, Database } from 'sqlite'; // Importar Database de sqlite
import path from 'path';

// Asegúrate de que el directorio 'data' exista en la raíz del proyecto para la persistencia.
// Docker montará un volumen aquí.
const DB_PATH = path.join(__dirname, '../data/app.db');

export async function openDb(): Promise<Database> { // Especificar tipo de retorno
    return open({
        filename: DB_PATH,
        driver: sqlite3.Database
    });
}

export async function initializeDb() {
    const db = await openDb();
    try {
        await db.exec(`
            CREATE TABLE IF NOT EXISTS users ( id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT, google_id TEXT UNIQUE, intra_id TEXT UNIQUE, is_active BOOLEAN DEFAULT 1, is_admin BOOLEAN DEFAULT 0, last_login DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS user_profiles ( user_id INTEGER PRIMARY KEY, avatar_url TEXT, bio TEXT, language TEXT DEFAULT 'es', notifications BOOLEAN DEFAULT 1, sound BOOLEAN DEFAULT 1, difficulty INTEGER DEFAULT 2, theme TEXT DEFAULT 'light', FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
            CREATE TABLE IF NOT EXISTS sessions ( id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, session_token TEXT UNIQUE NOT NULL, expires_at DATETIME NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
            CREATE TABLE IF NOT EXISTS friendships ( id INTEGER PRIMARY KEY AUTOINCREMENT, requester_id INTEGER NOT NULL, approver_id INTEGER, status TEXT DEFAULT 'pending', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (approver_id) REFERENCES users(id) ON DELETE CASCADE);
            CREATE TABLE IF NOT EXISTS chat_messages ( id INTEGER PRIMARY KEY AUTOINCREMENT, sender_id INTEGER NOT NULL, receiver_id INTEGER, message TEXT NOT NULL, sent_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE);
            CREATE TABLE IF NOT EXISTS tournaments ( id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, created_by INTEGER, status TEXT DEFAULT 'upcoming', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL);
            CREATE TABLE IF NOT EXISTS games ( id INTEGER PRIMARY KEY AUTOINCREMENT, tournament_id INTEGER, status TEXT DEFAULT 'pending', started_at DATETIME, finished_at DATETIME, FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE SET NULL);
            CREATE TABLE IF NOT EXISTS participants ( id INTEGER PRIMARY KEY AUTOINCREMENT, game_id INTEGER NOT NULL, user_id INTEGER, is_bot BOOLEAN DEFAULT 0, is_winner BOOLEAN DEFAULT 0, team_name TEXT NOT NULL, FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL);
            CREATE TABLE IF NOT EXISTS scores (id INTEGER PRIMARY KEY AUTOINCREMENT, game_id INTEGER NOT NULL, scorer_id INTEGER, team_name TEXT NOT NULL, point_number INTEGER NOT NULL, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,  FOREIGN KEY (scorer_id) REFERENCES users(id) ON DELETE SET NULL);
            CREATE TABLE IF NOT EXISTS user_stats ( user_id INTEGER PRIMARY KEY, gamesplayed INTEGER DEFAULT 0, games_won INTEGER DEFAULT 0, game_lost INTEGER DEFAULT 0, best_score INTEGER DEFAULT 0, total_points INTEGER DEFAULT 0, received_points INTEGER DEFAULT 0, win_rate REAL DEFAULT 0.0, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
            INSERT OR IGNORE INTO users (id, username, email, password_hash, created_at) VALUES (1, 'Manu', 'ardeiro@outlook.com', '$2b$12$U.2UHoDtA3/oeQHQIrznVuBokjoVRTfdv2zM7Qv7E3H0AldZ1Qhbe', datetime('now', '-1 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, created_at) VALUES (2, 'Ardeiro', 'ardeiro@gmail.com', '$2b$12$/1r9td3OkeutXq16OoALGuUeEO/nCCX4AwLvFJ2ZYZNWEuzkMyzEG', datetime('now', '-2 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, created_at) VALUES (3, 'HAL7000', 'manuel.ardeiro@gmail.com', '$2b$12$RagfU1ULf9zvoZBRqcQ5XOb.EgZybLX2mfr9W3gaKYiWiTUzi5sC6', datetime('now', '-3 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, created_at) VALUES (4, 'Verdu', 'jorge.verdu.ruiz@gmail.com', '$2b$12$fmkXJsqahw1S9bM8fQ6G3uhnDCfrLZlUwvKlKmr5SASA7AbX6kQZq', datetime('now', '-4 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, created_at) VALUES (5, 'David', 'david.aparicio247@hotmail.com', '$2b$12$iASlBV76WELxwwjOUmWeM.FjqHuDhkWQEEbTBBNRZb4B6/tEfyCmC', datetime('now', '-5 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, created_at) VALUES (6, 'ManuFern', 'manufern@student.42madrid.com', '$2b$12$1Mqudh5FrajQHKxtBOG26O/dL47xnZrbbQ8HjcipegON1NQdMFXou', datetime('now', '-6 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, created_at) VALUES (7, 'Diego', 'diegorubiomorato@gmail.com', '$2b$12$SC.8HYivrjOrLQQscZz7SuBNY4vodoHRh.cWXQ0htB/vBBJxblJPa', datetime('now', '-7 days'));
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, bio, language, notifications, sound, difficulty, theme) VALUES (1, NULL, '', 'es', 1, 1, 2, 'light');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, bio, language, notifications, sound, difficulty, theme) VALUES (2, NULL, '', 'es', 1, 1, 2, 'light');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, bio, language, notifications, sound, difficulty, theme) VALUES (3, NULL, '', 'es', 1, 1, 2, 'light');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, bio, language, notifications, sound, difficulty, theme) VALUES (4, NULL, '', 'es', 1, 1, 2, 'light');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, bio, language, notifications, sound, difficulty, theme) VALUES (5, NULL, '', 'es', 1, 1, 2, 'light');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, bio, language, notifications, sound, difficulty, theme) VALUES (6, NULL, '', 'es', 1, 1, 2, 'light');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, bio, language, notifications, sound, difficulty, theme) VALUES (7, NULL, '', 'es', 1, 1, 2, 'light');
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (1, 1, 2, 'accepted', datetime('now', '-1 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (2, 3, 4, 'accepted', datetime('now', '-2 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (3, 2, 7, 'accepted', datetime('now', '-3 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (4, 1, 5, 'accepted', datetime('now', '-4 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (5, 3, 7, 'accepted', datetime('now', '-5 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (6, 4, 6, 'accepted', datetime('now', '-6 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (7, 1, 4, 'accepted', datetime('now', '-7 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (8, 5, 7, 'accepted', datetime('now', '-8 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (9, 6, 7, 'accepted', datetime('now', '-9 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (10, 1, 7, 'accepted', datetime('now', '-10 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (11, 4, 5, 'accepted', datetime('now', '-11 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (12, 5, 6, 'accepted', datetime('now', '-12 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (13, 3, 6, 'accepted', datetime('now', '-13 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (14, 2, 5, 'accepted', datetime('now', '-14 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (15, 1, 3, 'accepted', datetime('now', '-15 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (16, 4, 7, 'accepted', datetime('now', '-16 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (17, 3, 5, 'accepted', datetime('now', '-17 hours'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (1, 'Torneo 1', 2, 'completed', datetime('now', '-1 days'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (2, 'Torneo 2', 6, 'completed', datetime('now', '-2 days'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (3, 'Torneo 3', 4, 'completed', datetime('now', '-3 days'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (4, 'Torneo 4', 1, 'completed', datetime('now', '-4 days'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (5, 'Torneo 5', 6, 'completed', datetime('now', '-5 days'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (1, 'finished', '2025-07-08 08:47:09.083019', '2025-07-08 08:54:35.083019');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (2, 'finished', '2025-07-04 08:47:09.083138', '2025-07-04 08:53:13.083138');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (3, 'finished', '2025-06-18 08:47:09.083191', '2025-06-18 08:53:44.083191');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (4, 'finished', '2025-05-30 08:47:09.083235', '2025-05-30 08:51:08.083235');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (5, 'finished', '2025-06-05 08:47:09.083262', '2025-06-05 08:51:43.083262');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (6, 'finished', '2025-06-19 08:47:09.083300', '2025-06-19 08:54:10.083300');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (7, 'finished', '2025-05-18 08:47:09.083336', '2025-05-18 08:53:40.083336');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (8, 'finished', '2025-06-19 08:47:09.083374', '2025-06-19 08:53:23.083374');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (9, 'finished', '2025-05-19 08:47:09.083411', '2025-05-19 08:49:32.083411');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (10, 'finished', '2025-07-04 08:47:09.083464', '2025-07-04 08:49:39.083464');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (11, 'finished', '2025-05-31 08:47:09.083498', '2025-05-31 08:55:47.083498');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (12, 'finished', '2025-06-28 08:47:09.083552', '2025-06-28 08:50:37.083552');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (13, 'finished', '2025-05-26 08:47:09.083604', '2025-05-26 08:51:18.083604');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (14, 'finished', '2025-06-07 08:47:09.083820', '2025-06-07 08:54:35.083820');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (15, 'finished', '2025-06-22 08:47:09.083856', '2025-06-22 08:49:51.083856');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (16, 'finished', '2025-06-12 08:47:09.083890', '2025-06-12 08:52:44.083890');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (17, 'finished', '2025-07-13 08:47:09.083923', '2025-07-13 08:55:22.083923');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (18, 'finished', '2025-06-16 08:47:09.083962', '2025-06-16 08:56:41.083962');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (19, 'finished', '2025-07-01 08:47:09.083994', '2025-07-01 08:52:36.083994');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (20, 'finished', '2025-06-19 08:47:09.084025', '2025-06-19 08:56:32.084025');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (21, 'finished', '2025-06-30 08:47:09.084045', '2025-06-30 08:50:27.084045');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (22, 'finished', '2025-07-01 08:47:09.084064', '2025-07-01 08:57:02.084064');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (23, 'finished', '2025-06-01 08:47:09.084093', '2025-06-01 08:54:33.084093');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (24, 'finished', '2025-06-12 08:47:09.084129', '2025-06-12 08:52:22.084129');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (25, 'finished', '2025-05-18 08:47:09.084169', '2025-05-18 08:54:50.084169');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (26, 'finished', '2025-05-19 08:47:09.084199', '2025-05-19 08:55:28.084199');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (27, 'finished', '2025-07-12 08:47:09.084235', '2025-07-12 08:51:29.084235');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (28, 'finished', '2025-06-05 08:47:09.084292', '2025-06-05 08:49:34.084292');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (29, 'finished', '2025-06-03 08:47:09.084349', '2025-06-03 08:51:03.084349');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (30, 'finished', '2025-06-30 08:47:09.084385', '2025-06-30 08:55:34.084385');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (31, 'finished', '2025-07-02 08:47:09.084420', '2025-07-02 08:56:24.084420');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (32, 'finished', '2025-05-22 08:47:09.084453', '2025-05-22 08:53:48.084453');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (33, 'finished', '2025-07-03 08:47:09.084484', '2025-07-03 08:49:29.084484');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (34, 'finished', '2025-05-29 08:47:09.084526', '2025-05-29 08:52:02.084526');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (35, 'finished', '2025-06-20 08:47:09.084556', '2025-06-20 08:51:17.084556');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (36, 'finished', '2025-06-07 08:47:09.084576', '2025-06-07 08:56:59.084576');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (37, 'finished', '2025-06-01 08:47:09.084603', '2025-06-01 08:48:23.084603');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (38, 'finished', '2025-07-02 08:47:09.084636', '2025-07-02 08:52:36.084636');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (39, 'finished', '2025-07-12 08:47:09.084676', '2025-07-12 08:52:32.084676');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (40, 'finished', '2025-05-23 08:47:09.084717', '2025-05-23 08:51:26.084717');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (41, 'finished', '2025-06-03 08:47:09.084740', '2025-06-03 08:48:36.084740');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (42, 'finished', '2025-06-04 08:47:09.084766', '2025-06-04 08:48:27.084766');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (43, 'finished', '2025-05-31 08:47:09.084798', '2025-05-31 08:52:37.084798');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (44, 'finished', '2025-06-02 08:47:09.084830', '2025-06-02 08:57:02.084830');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (45, 'finished', '2025-06-05 08:47:09.084854', '2025-06-05 08:53:13.084854');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (46, 'finished', '2025-06-15 08:47:09.084888', '2025-06-15 08:55:20.084888');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (47, 'finished', '2025-06-22 08:47:09.084943', '2025-06-22 08:56:40.084943');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (48, 'finished', '2025-05-24 08:47:09.084977', '2025-05-24 08:51:54.084977');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (49, 'finished', '2025-06-07 08:47:09.085010', '2025-06-07 08:50:25.085010');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (50, 'finished', '2025-05-26 08:47:09.085047', '2025-05-26 08:55:36.085047');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (51, 'finished', '2025-05-18 08:47:09.085567', '2025-05-18 08:49:06.085567');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (52, 'finished', '2025-05-27 08:47:09.085630', '2025-05-27 08:51:24.085630');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (53, 'finished', '2025-06-04 08:47:09.085670', '2025-06-04 08:52:18.085670');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (54, 'finished', '2025-05-29 08:47:09.085689', '2025-05-29 08:49:05.085689');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (55, 'finished', '2025-07-07 08:47:09.085896', '2025-07-07 08:51:28.085896');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (56, 'finished', '2025-05-29 08:47:09.085932', '2025-05-29 08:48:09.085932');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (57, 'finished', '2025-06-14 08:47:09.085960', '2025-06-14 08:52:47.085960');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (58, 'finished', '2025-06-02 08:47:09.085987', '2025-06-02 08:48:53.085987');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (59, 'finished', '2025-06-05 08:47:09.086011', '2025-06-05 08:51:39.086011');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (60, 'finished', '2025-06-11 08:47:09.086035', '2025-06-11 08:53:42.086035');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (61, 'finished', '2025-06-04 08:47:09.086084', '2025-06-04 08:53:19.086084');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (62, 'finished', '2025-06-04 08:47:09.086110', '2025-06-04 08:52:35.086110');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (63, 1, 'completed', '2025-07-10 09:31:02.895139', '2025-07-10 09:39:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (64, 1, 'completed', '2025-07-10 07:31:02.895139', '2025-07-10 07:34:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (65, 1, 'completed', '2025-07-10 05:31:02.895139', '2025-07-10 05:34:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (66, 2, 'completed', '2025-07-11 09:31:02.895139', '2025-07-11 09:38:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (67, 2, 'completed', '2025-07-11 07:31:02.895139', '2025-07-11 07:40:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (68, 2, 'completed', '2025-07-11 05:31:02.895139', '2025-07-11 05:37:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (69, 3, 'completed', '2025-07-12 09:31:02.895139', '2025-07-12 09:36:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (70, 3, 'completed', '2025-07-12 07:31:02.895139', '2025-07-12 07:36:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (71, 3, 'completed', '2025-07-12 05:31:02.895139', '2025-07-12 05:34:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (72, 4, 'completed', '2025-07-13 09:31:02.895139', '2025-07-13 09:38:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (73, 4, 'completed', '2025-07-13 07:31:02.895139', '2025-07-13 07:39:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (74, 4, 'completed', '2025-07-13 05:31:02.895139', '2025-07-13 05:39:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (75, 5, 'completed', '2025-07-14 09:31:02.895139', '2025-07-14 09:40:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (76, 5, 'completed', '2025-07-14 07:31:02.895139', '2025-07-14 07:40:02.895139');
            INSERT OR IGNORE INTO games (id, tournament_id, status, started_at, finished_at) VALUES (77, 5, 'completed', '2025-07-14 05:31:02.895139', '2025-07-14 05:39:02.895139');
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (78,'finished',datetime('now','-21 hours'),datetime('now','-20 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (79,'finished',datetime('now','-20 hours'),datetime('now','-19 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (80,'finished',datetime('now','-19 hours'),datetime('now','-18 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (81,'finished',datetime('now','-18 hours'),datetime('now','-17 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (82,'finished',datetime('now','-17 hours'),datetime('now','-16 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (83,'finished',datetime('now','-16 hours'),datetime('now','-15 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (84,'finished',datetime('now','-15 hours'),datetime('now','-14 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (85,'finished',datetime('now','-14 hours'),datetime('now','-13 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (86,'finished',datetime('now','-13 hours'),datetime('now','-12 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (87,'finished',datetime('now','-12 hours'),datetime('now','-11 hours'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (88,'finished',datetime('now','-11 hours'),datetime('now','-10 hours'));
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (1, 1, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (2, 1, 6, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (3, 2, 4, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (4, 2, 5, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (5, 3, 6, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (6, 3, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (7, 4, 4, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (8, 4, 7, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (9, 5, 5, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (10, 5, 1, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (11, 6, 1, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (12, 6, 3, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (13, 7, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (14, 7, 6, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (15, 8, 7, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (16, 8, 2, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (17, 9, 6, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (18, 9, 3, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (19, 10, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (20, 10, 1, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (21, 11, 1, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (22, 11, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (23, 12, 3, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (24, 12, 6, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (25, 13, 6, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (26, 13, 2, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (27, 14, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (28, 14, 1, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (29, 15, 3, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (30, 15, 1, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (31, 16, 6, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (32, 16, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (33, 17, 6, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (34, 17, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (35, 18, 1, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (36, 18, 3, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (37, 19, 5, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (38, 19, 6, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (39, 20, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (40, 20, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (41, 21, 4, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (42, 21, 2, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (43, 22, 3, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (44, 22, 6, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (45, 23, 5, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (46, 23, 7, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (47, 24, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (48, 24, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (49, 25, 7, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (50, 25, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (51, 26, 4, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (52, 26, 3, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (53, 27, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (54, 27, 1, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (55, 28, 1, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (56, 28, 7, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (57, 29, 6, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (58, 29, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (59, 30, 5, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (60, 30, 3, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (61, 31, 4, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (62, 31, 3, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (63, 32, 5, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (64, 32, 3, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (65, 33, 4, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (66, 33, 5, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (67, 34, 4, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (68, 34, 1, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (69, 35, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (70, 35, 3, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (71, 36, 5, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (72, 36, 7, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (73, 37, 6, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (74, 37, 2, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (75, 38, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (76, 38, 3, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (77, 39, 5, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (78, 39, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (79, 40, 1, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (80, 40, 6, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (81, 41, 7, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (82, 41, 5, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (83, 42, 1, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (84, 42, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (85, 43, 3, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (86, 43, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (87, 44, 6, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (88, 44, 5, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (89, 45, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (90, 45, 1, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (91, 46, 7, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (92, 46, 2, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (93, 47, 7, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (94, 47, 1, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (95, 48, 3, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (96, 48, 2, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (97, 49, 7, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (98, 49, 4, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (99, 50, 1, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (100, 50, 6, 0, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (101, 51, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (102, 51, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (103, 52, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (104, 52, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (105, 53, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (106, 53, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (107, 54, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (108, 54, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (109, 55, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (110, 55, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (111, 56, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (112, 56, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (113, 57, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (114, 57, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (115, 58, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (116, 58, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (117, 59, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (118, 59, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (119, 60, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (120, 60, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (121, 61, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (122, 61, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (123, 62, 2, 0, 1, 'A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (124, 62, NULL, 1, 0, 'B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (125, 63, 3, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (126, 63, 7, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (127, 64, 5, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (128, 64, 3, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (129, 65, 2, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (130, 65, 6, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (131, 66, 2, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (132, 66, 1, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (133, 67, 4, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (134, 67, 1, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (135, 68, 2, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (136, 68, 5, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (137, 69, 2, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (138, 69, 1, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (139, 70, 2, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (140, 70, 5, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (141, 71, 3, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (142, 71, 1, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (143, 72, 4, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (144, 72, 5, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (145, 73, 5, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (146, 73, 1, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (147, 74, 2, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (148, 74, 6, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (149, 75, 5, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (150, 75, 1, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (151, 76, 5, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (152, 76, 4, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (153, 77, 2, 0, 1, 'Equipo A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (154, 77, 3, 0, 0, 'Equipo B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (155,78,1,0,1,'Team_1');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (156,78,NULL,1,0,'BOT_78');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (157,79,1,0,0,'Team_1');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (158,79,NULL,1,1,'BOT_79');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (159,80,1,0,1,'Team_1');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (160,80,NULL,1,0,'BOT_80');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (161,81,2,0,1,'Team_2');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (162,81,NULL,1,0,'BOT_81');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (163,82,2,0,0,'Team_2');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (164,82,NULL,1,1,'BOT_82');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (165,83,2,0,1,'Team_2');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (166,83,NULL,1,0,'BOT_83');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (167,84,3,0,1,'Team_3');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (168,84,NULL,1,0,'BOT_84');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (169,85,3,0,0,'Team_3');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (170,85,NULL,1,1,'BOT_85');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (171,86,3,0,1,'Team_3');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (172,86,NULL,1,0,'BOT_86');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (173,87,4,0,1,'Team_4');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (174,87,NULL,1,0,'BOT_87');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (175,88,4,0,0,'Team_4');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (176,88,NULL,1,1,'BOT_88');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (1, 1, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (2, 1, 4, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (3, 2, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (4, 2, 1, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (5, 3, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (6, 3, 3, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (7, 4, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (8, 4, 7, 'B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (9, 5, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (10, 5, 3, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (11, 6, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (12, 6, 5, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (13, 7, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (14, 7, 6, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (15, 8, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (16, 8, 6, 'B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (17, 9, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (18, 9, 6, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (19, 10, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (20, 10, 4, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (21, 11, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (22, 11, 3, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (23, 12, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (24, 12, 7, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (25, 13, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (26, 13, 5, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (27, 14, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (28, 14, 5, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (29, 15, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (30, 15, 5, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (31, 16, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (32, 16, 7, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (33, 17, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (34, 17, 1, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (35, 18, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (36, 18, 4, 'B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (37, 19, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (38, 19, 7, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (39, 20, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (40, 20, 1, 'B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (41, 21, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (42, 21, 1, 'B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (43, 22, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (44, 22, 3, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (45, 23, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (46, 23, 4, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (47, 24, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (48, 24, 3, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (49, 25, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (50, 25, 6, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (51, 26, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (52, 26, 5, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (53, 27, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (54, 27, 4, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (55, 28, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (56, 28, 7, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (57, 29, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (58, 29, 6, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (59, 30, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (60, 30, 3, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (61, 31, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (62, 31, 6, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (63, 32, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (64, 32, 3, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (65, 33, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (66, 33, 7, 'B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (67, 34, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (68, 34, 1, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (69, 35, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (70, 35, 4, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (71, 36, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (72, 36, 3, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (73, 37, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (74, 37, 5, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (75, 38, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (76, 38, 5, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (77, 39, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (78, 39, 6, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (79, 40, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (80, 40, 6, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (81, 41, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (82, 41, 3, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (83, 42, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (84, 42, 7, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (85, 43, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (86, 43, 6, 'B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (87, 44, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (88, 44, 7, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (89, 45, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (90, 45, 4, 'B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (91, 46, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (92, 46, 6, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (93, 47, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (94, 47, 4, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (95, 48, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (96, 48, 4, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (97, 49, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (98, 49, 6, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (99, 50, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (100, 50, 3, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (101, 51, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (102, 51, 6, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (103, 52, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (104, 52, 7, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (105, 53, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (106, 53, 4, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (107, 54, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (108, 54, 5, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (109, 55, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (110, 55, 4, 'B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (111, 56, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (112, 56, 3, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (113, 57, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (114, 57, 6, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (115, 58, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (116, 58, 7, 'B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (117, 59, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (118, 59, 4, 'B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (119, 60, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (120, 60, 3, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (121, 61, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (122, 61, 3, 'B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (123, 62, 2, 'A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (124, 62, 3, 'B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (125, 63, 3, 'Equipo A', 5, '2025-07-14 10:00:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (126, 63, 7, 'Equipo B', 4, '2025-07-14 10:00:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (127, 64, 5, 'Equipo A', 5, '2025-07-14 10:01:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (128, 64, 3, 'Equipo B', 3, '2025-07-14 10:01:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (129, 65, 2, 'Equipo A', 5, '2025-07-14 10:02:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (130, 65, 6, 'Equipo B', 4, '2025-07-14 10:02:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (131, 66, 2, 'Equipo A', 5, '2025-07-14 10:03:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (132, 66, 1, 'Equipo B', 0, '2025-07-14 10:03:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (133, 67, 4, 'Equipo A', 5, '2025-07-14 10:04:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (134, 67, 1, 'Equipo B', 1, '2025-07-14 10:04:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (135, 68, 2, 'Equipo A', 5, '2025-07-14 10:05:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (136, 68, 5, 'Equipo B', 2, '2025-07-14 10:05:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (137, 69, 2, 'Equipo A', 5, '2025-07-14 10:06:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (138, 69, 1, 'Equipo B', 3, '2025-07-14 10:06:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (139, 70, 2, 'Equipo A', 5, '2025-07-14 10:07:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (140, 70, 5, 'Equipo B', 1, '2025-07-14 10:07:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (141, 71, 3, 'Equipo A', 5, '2025-07-14 10:08:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (142, 71, 1, 'Equipo B', 4, '2025-07-14 10:08:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (143, 72, 4, 'Equipo A', 5, '2025-07-14 10:09:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (144, 72, 5, 'Equipo B', 1, '2025-07-14 10:09:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (145, 73, 5, 'Equipo A', 5, '2025-07-14 10:10:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (146, 73, 1, 'Equipo B', 1, '2025-07-14 10:10:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (147, 74, 2, 'Equipo A', 5, '2025-07-14 10:11:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (148, 74, 6, 'Equipo B', 4, '2025-07-14 10:11:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (149, 75, 5, 'Equipo A', 5, '2025-07-14 10:12:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (150, 75, 1, 'Equipo B', 2, '2025-07-14 10:12:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (151, 76, 5, 'Equipo A', 5, '2025-07-14 10:13:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (152, 76, 4, 'Equipo B', 4, '2025-07-14 10:13:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (153, 77, 2, 'Equipo A', 5, '2025-07-14 10:14:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number, timestamp) VALUES (154, 77, 3, 'Equipo B', 0, '2025-07-14 10:14:00');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (155,78,1,'Team_1',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (156,78,NULL,'BOT_78',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (157,79,1,'Team_1',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (158,79,NULL,'BOT_79',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (159,80,1,'Team_1',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (160,80,NULL,'BOT_80',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (161,81,2,'Team_2',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (162,81,NULL,'BOT_81',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (163,82,2,'Team_2',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (164,82,NULL,'BOT_82',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (165,83,2,'Team_2',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (166,83,NULL,'BOT_83',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (167,84,3,'Team_3',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (168,84,NULL,'BOT_84',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (169,85,3,'Team_3',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (170,85,NULL,'BOT_85',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (171,86,3,'Team_3',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (172,86,NULL,'BOT_86',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (173,87,4,'Team_4',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (174,87,NULL,'BOT_87',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (175,88,4,'Team_4',1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (176,88,NULL,'BOT_88',1);
        `);
        console.log('Base de datos inicializada y tablas creadas (si no existían).');
    } finally {
        await db.close();
    }
}
