version: '3.8'

services:
  # Servicio para el frontend (tu juego Pong)
  frontend:
    build:
      context: . # El contexto es el directorio actual donde está este docker-compose.yml
      dockerfile: Dockerfile # Usa el Dockerfile en el directorio raíz
    ports:
      - "8080:80" # Mapea el puerto 8080 del host al puerto 80 del contenedor Nginx


