services:
  tournament-service:
    build: ./tournament-service
    image: tournament-service
    container_name: tournament-service
    ports:
      - "8004:8000" # Mapea el puerto 8000 interno a 8004 en el host
    environment:
      DB_SERVICE_URL: "http://db-service:8005"
      GAME_SERVICE_URL: "http://game-service:8000"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - db-service
      - game-service
      - redis
    networks:
      - transcendence_net
    restart: on-failure
  # Servicio de Autenticación y Perfiles de Usuario
  auth-service:
    build: ./auth-service
    image: auth-service
    container_name: auth-service
    ports:
      - "8001:8000" # Mapea el puerto 8000 interno a 8001 en el host
    environment:
      DB_SERVICE_URL: "http://db-service:8005"
      VAULT_ADDR: "http://vault:8200"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - db-service
      - vault
    volumes:
      - db_data:/app/data
    networks:
      - transcendence_net
    restart: on-failure

  # Servicio de Juego (Pong)
  game-service:
    build: ./game-service
    image: game-service
    container_name: game-service
    ports:
      - "8002:8000" # Mapea el puerto 8000 interno a 8002 en el host
    environment:
      DB_SERVICE_URL: "http://db-service:8005"
      VAULT_ADDR: "http://vault:8200"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - db-service
      - auth-service
      - vault
      - redis
    networks:
      - transcendence_net
    restart: on-failure

  # Servicio de Chat
  chat-service:
    build: ./chat-service
    image: chat-service
    container_name: chat-service
    ports:
      - "8003:8000" # Mapea el puerto 8000 interno a 8003 en el host
    environment:
      DB_SERVICE_URL: "http://db-service:8005"
      VAULT_ADDR: "http://vault:8200"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - db-service
      - auth-service
      - vault
      - redis
    networks:
      - transcendence_net
    restart: on-failure

  # Pasarela API (API Gateway)
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "9000:8000" # Mapea el puerto 8000 interno a 9000 en el host
    environment:
      AUTH_SERVICE_URL: "${AUTH_SERVICE_URL}"
      GAME_SERVICE_URL: "${GAME_SERVICE_URL}"
      CHAT_SERVICE_URL: "${CHAT_SERVICE_URL}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - auth-service
      - game-service
      - chat-service
      - redis
    networks:
      - transcendence_net
    restart: on-failure

  # Frontend
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - "9001:8080" # Main web access on port 80
    depends_on:
      - api-gateway
    networks:
      - transcendence_net
    restart: on-failure

  # HashiCorp Vault
  vault:
    image: hashicorp/vault:latest
    container_name: hashicorp_vault
    ports:
      - "8200:8200" # Vault ya usa un puerto no privilegiado por defecto
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "dev-root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - transcendence_net
    restart: on-failure

  # WAF (Web Application Firewall) - Nginx con ModSecurity como ejemplo
  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: WAF
    ports:
      - "9002:8080" # El WAF escuchará en 9002 en el host
    environment:
      MODSECURITY_RULES_PATH: "/etc/nginx/modsecurity/modsecurity.conf"
      BACKEND: "http://frontend:8080" # Apunta al puerto interno del frontend
      SSL_STAPLING: "off" # Disable SSL stapling to remove warning
      PARANOIA: "1" # Set paranoia level to reduce false positives
      ANOMALY_INBOUND: "10" # Set anomaly scoring threshold
      ANOMALY_OUTBOUND: "5" # Set anomaly scoring threshold
      # CORS configuration properties
      CORS_HEADER_ACCESS_CONTROL_ALLOW_HEADERS: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
      CORS_HEADER_403_CONTENT_TYPE: "text/plain"
      CORS_HEADER_403_ALLOW_ORIGIN: "*"
      CORS_HEADER_403_MAX_AGE: "1728000"
      CORS_HEADER_403_ALLOW_METHODS: "GET, POST, PUT, DELETE, OPTIONS"
    # volumes:
      # - ./nginx-waf/modsecurity.conf:/etc/modsecurity.d/modsecurity-override.conf:ro
      # - ./nginx-waf/proxy_backend.conf:/etc/nginx/templates/conf.d/proxy_backend.conf.template:ro
    depends_on:
      - frontend
    networks:
      - transcendence_net
    restart: on-failure
    user: "0:0" # Run as root to ensure proper permissions

  # Nginx Reverse Proxy for standard ports
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./ssl/localhost.key:/etc/ssl/private/localhost.key:ro
    depends_on:
      - waf
      - api-gateway
    networks:
      - transcendence_net
    restart: on-failure

  # Servicio de Base de Datos (API de acceso a SQLite)
  db-service:
    build: ./db-service
    image: db-service
    container_name: db-service
    ports:
      - "8005:8000" # Mapea el puerto 8000 interno a 8005 en el host
    volumes:
      - db_data:/app/data # Monta un volumen para persistir la base de datos SQLite
    environment:
      VAULT_ADDR: "http://vault:8200"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - vault
      - redis
    networks:
      - transcendence_net
    restart: on-failure
  redis:
    build:
      context: ./db-service/redis
    image: redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    secrets:
      - redis_password
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "o-meu-contrasinal.42", "--maxmemory", "256mb"]
    networks:
      - transcendence_net
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    environment:
      - REDIS_HOSTS=redis:redis:6379:0:${REDIS_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - transcendence_net
  sqlite-writer:
    build: ./db-service/sqlite-writer
    image: sqlite-writer
    container_name: sqlite-writer
    depends_on:
      - redis
      - db-service
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    secrets:
      - redis_password
    volumes:
      - db_data:/app/data
    restart: on-failure
    networks:
      - transcendence_net



secrets:
  redis_password:
    file: ./secrets/redis/password.txt

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/sqlite
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/redis

networks:
  transcendence_net:
    name: transcendence_net 
    driver: bridge
