apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus-transcendence
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "10s"
