global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@transcendence.local'
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'critical-notifications'
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-notifications'
      repeat_interval: 1h

receivers:
  - name: 'default-notifications'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook/alerts'
        send_resolved: true
        http_config:
          timeout: 10s
        title: 'Transcendence Alert'
        text: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Service:** {{ .Labels.job }}
          **Instance:** {{ .Labels.instance }}
          {{ end }}

  - name: 'critical-notifications'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook/critical'
        send_resolved: true
        title: '🚨 CRITICAL ALERT - Transcendence'
        
  - name: 'warning-notifications'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook/warning'
        send_resolved: true
        title: '⚠️ WARNING - Transcendence'

  # Email notifications (configure SMTP details in .env)
  # - name: 'email-notifications'
  #   email_configs:
  #     - to: 'admin@transcendence.local'
  #       subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
  #       body: |
  #         {{ range .Alerts }}
  #         **Alert:** {{ .Annotations.summary }}
  #         **Description:** {{ .Annotations.description }}
  #         **Severity:** {{ .Labels.severity }}
  #         **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
  #         {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
