global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ft_transcendence'
    replica: 'prometheus-1'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Dedicated exporters (these have native Prometheus metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # HashiCorp Vault (has native Prometheus metrics)
  - job_name: 'vault'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['vault:8200']
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    bearer_token: 'dev-root-token'
    scrape_interval: 60s

  # Blackbox exporter self-monitoring
  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['blackbox-exporter:9115']

  # Blackbox exporter probes for HTTP health checks
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://waf:8080         # WAF (frontend through WAF)
          - http://redis-commander:8081  # redis-commander
          - http://nginx-proxy:80   # nginx-proxy
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Blackbox exporter probes for TCP connectivity checks
  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - game-service:8000  # game-service
          - api-gateway:8000   # api-gateway
          - auth-service:8000  # auth-service
          - chat-service:8000  # chat-service
          - db-service:8000    # db-service
          - redis:6379         # redis
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
