import sqlite3 from 'sqlite3';
import { open, Database } from 'sqlite'; // Importar Database de sqlite
import path from 'path';

// Asegúrate de que el directorio 'data' exista en la raíz del proyecto para la persistencia.
// Docker montará un volumen aquí.
const DB_PATH = path.join(__dirname, '../data/app.db');

export async function openDb(): Promise<Database> { // Especificar tipo de retorno
    return open({
        filename: DB_PATH,
        driver: sqlite3.Database
    });
}

export async function initializeDb() {
    const db = await openDb();
    try {
        await db.exec(`
            CREATE TABLE IF NOT EXISTS users ( id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT, google_id TEXT UNIQUE, intra_id TEXT UNIQUE, is_active BOOLEAN DEFAULT 1, is_admin BOOLEAN DEFAULT 0, last_login DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS user_profiles ( user_id INTEGER PRIMARY KEY, avatar_url TEXT, language TEXT DEFAULT 'es', notifications TEXT DEFAULT 'true', doubleFactor BOOLEAN DEFAULT 'false', doubleFactorSecret TEXT DEFAULT NULL, difficulty TEXT DEFAULT 'normal', FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
            CREATE TABLE IF NOT EXISTS sessions ( id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, session_token TEXT UNIQUE NOT NULL, expires_at DATETIME NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
            CREATE TABLE IF NOT EXISTS friendships ( id INTEGER PRIMARY KEY AUTOINCREMENT, requester_id INTEGER NOT NULL, approver_id INTEGER, status TEXT DEFAULT 'pending', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (approver_id) REFERENCES users(id) ON DELETE CASCADE, UNIQUE(requester_id, approver_id));
            CREATE TABLE IF NOT EXISTS chat_messages ( id INTEGER PRIMARY KEY AUTOINCREMENT, sender_id INTEGER NOT NULL, receiver_id INTEGER, message TEXT NOT NULL, sent_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE);
            CREATE TABLE IF NOT EXISTS tournaments ( id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, created_by INTEGER, status TEXT DEFAULT 'upcoming', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL);
            CREATE TABLE IF NOT EXISTS games ( id INTEGER PRIMARY KEY AUTOINCREMENT, tournament_id INTEGER, match TEXT, status TEXT DEFAULT 'pending', started_at DATETIME, finished_at DATETIME, FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE SET NULL);
            CREATE TABLE IF NOT EXISTS participants ( id INTEGER PRIMARY KEY AUTOINCREMENT, game_id INTEGER NOT NULL, user_id INTEGER, is_bot BOOLEAN DEFAULT 0, is_winner BOOLEAN DEFAULT 0, team_name TEXT NOT NULL, FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL);
            CREATE TABLE IF NOT EXISTS scores (id INTEGER PRIMARY KEY AUTOINCREMENT, game_id INTEGER NOT NULL, scorer_id INTEGER, team_name TEXT NOT NULL, point_number INTEGER NOT NULL, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,  FOREIGN KEY (scorer_id) REFERENCES users(id) ON DELETE SET NULL);            
            INSERT OR IGNORE INTO users (id, username, email, password_hash, is_active, is_admin, created_at) VALUES (1, 'Manu', 'ardeiro@outlook.com', '$2b$12$U.2UHoDtA3/oeQHQIrznVuBokjoVRTfdv2zM7Qv7E3H0AldZ1Qhbe', 1, 1, datetime('now', '-1 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, is_active, is_admin, created_at) VALUES (2, 'Ardeiro', 'ardeiro@gmail.com', '$2b$12$/1r9td3OkeutXq16OoALGuUeEO/nCCX4AwLvFJ2ZYZNWEuzkMyzEG', 1, 1, datetime('now', '-2 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, is_active, is_admin, created_at) VALUES (3, 'HAL7000', 'manuel.ardeiro@gmail.com', '$2b$12$RagfU1ULf9zvoZBRqcQ5XOb.EgZybLX2mfr9W3gaKYiWiTUzi5sC6', 1, 1, datetime('now', '-3 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, is_active, is_admin, created_at) VALUES (4, 'Verdu', 'jorge.verdu.ruiz@gmail.com', '$2b$12$fmkXJsqahw1S9bM8fQ6G3uhnDCfrLZlUwvKlKmr5SASA7AbX6kQZq', 1, 1, datetime('now', '-4 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, is_active, is_admin, created_at) VALUES (5, 'David', 'david.aparicio247@hotmail.com', '$2b$12$iASlBV76WELxwwjOUmWeM.FjqHuDhkWQEEbTBBNRZb4B6/tEfyCmC', 1, 1, datetime('now', '-5 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, is_active, is_admin, created_at) VALUES (6, 'ManuFern', 'manufern@student.42madrid.com', '$2b$12$1Mqudh5FrajQHKxtBOG26O/dL47xnZrbbQ8HjcipegON1NQdMFXou', 1, 1, datetime('now', '-6 days'));
            INSERT OR IGNORE INTO users (id, username, email, password_hash, is_active, is_admin, created_at) VALUES (7, 'Diego', 'diegorubiomorato@gmail.com', '$2b$12$SC.8HYivrjOrLQQscZz7SuBNY4vodoHRh.cWXQ0htB/vBBJxblJPa', 1, 1, datetime('now', '-7 days'));
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, language, notifications, doubleFactor, difficulty) VALUES (1, NULL, 'es', 'true', 'false', 'normal');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, language, notifications, doubleFactor, difficulty) VALUES (2, NULL, 'gl', 'true', 'false', 'normal');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, language, notifications, doubleFactor, difficulty) VALUES (3, NULL, 'en', 'true', 'false', 'normal');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, language, notifications, doubleFactor, difficulty) VALUES (4, NULL, 'es', 'true', 'false', 'normal');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, language, notifications, doubleFactor, difficulty) VALUES (5, NULL, 'en', 'true', 'false', 'normal');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, language, notifications, doubleFactor, difficulty) VALUES (6, NULL, 'es', 'true', 'false', 'normal');
            INSERT OR IGNORE INTO user_profiles (user_id, avatar_url, language, notifications, doubleFactor, difficulty) VALUES (7, NULL, 'en', 'true', 'false', 'normal');
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (1, 1, 2, 'pending', datetime('now', '-1 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (2, 1, 4, 'accepted', datetime('now', '-2 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (3, 1, 6, 'accepted', datetime('now', '-3 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (4, 2, 3, 'accepted', datetime('now', '-4 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (5, 2, 4, 'accepted', datetime('now', '-5 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (6, 2, 5, 'pending', datetime('now', '-6 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (7, 7, 2, 'pending', datetime('now', '-7 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (8, 3, 1, 'accepted', datetime('now', '-8 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (9, 3, 4, 'accepted', datetime('now', '-9 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (10, 3, 6, 'pending', datetime('now', '-9 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (10, 5, 4, 'accepted', datetime('now', '-10 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (11, 4, 7, 'accepted', datetime('now', '-11 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (12, 5, 6, 'accepted', datetime('now', '-12 hours'));
            INSERT OR IGNORE INTO friendships (id, requester_id, approver_id, status, created_at) VALUES (13, 6, 7, 'accepted', datetime('now', '-13 hours'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (1, 'Torneo Relámpago', 1, 'finished', datetime('now', '-1 days'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (2, 'Copa Velocidad', 3, 'finished', datetime('now', '-2 days'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (3, 'Torneo Express', 2, 'finished', datetime('now', '-3 days'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (4, 'Desafío Rápido', 5, 'finished', datetime('now', '-4 days'));
            INSERT OR IGNORE INTO tournaments (id, name, created_by, status, created_at) VALUES (5, 'Torneo Flash', 7, 'finished', datetime('now', '-5 days'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (1, 1, '1/2(1)', 'finished', datetime('now', '-1 days', '15:00:00'), datetime('now', '-1 days', '15:00:00', '+7 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (2, 1, '1/2(2)', 'finished', datetime('now', '-1 days', '15:08:00'), datetime('now', '-1 days', '15:08:00', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (3, 1, 'Final', 'finished', datetime('now', '-1 days', '15:18:00'), datetime('now', '-1 days', '15:18:00', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (4, 2, '1/2(1)', 'finished', datetime('now', '-2 days', '16:00:00'), datetime('now', '-2 days', '16:00:00', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (5, 2, '1/2(2)', 'finished', datetime('now', '-2 days', '16:06:00'), datetime('now', '-2 days', '16:06:00', '+12 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (6, 2, 'Final', 'finished', datetime('now', '-2 days', '16:19:00'), datetime('now', '-2 days', '16:19:00', '+8 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (7, 3, '1/2(1)', 'finished', datetime('now', '-3 days', '17:30:00'), datetime('now', '-3 days', '17:30:00', '+4 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (8, 3, '1/2(2)', 'finished', datetime('now', '-3 days', '17:35:00'), datetime('now', '-3 days', '17:35:00', '+14 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (9, 3, 'Final', 'finished', datetime('now', '-3 days', '17:50:00'), datetime('now', '-3 days', '17:50:00', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (10, 4, '1/2(1)', 'finished', datetime('now', '-4 days', '18:00:00'), datetime('now', '-4 days', '18:00:00', '+6 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (11, 4, '1/2(2)', 'finished', datetime('now', '-4 days', '18:07:00'), datetime('now', '-4 days', '18:07:00', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (12, 4, 'Final', 'finished', datetime('now', '-4 days', '18:19:00'), datetime('now', '-4 days', '18:19:00', '+7 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (13, 5, '1/2(1)', 'finished', datetime('now', '-5 days', '19:00:00'), datetime('now', '-5 days', '19:00:00', '+10 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (14, 5, '1/2(2)', 'finished', datetime('now', '-5 days', '19:11:00'), datetime('now', '-5 days', '19:11:00', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, tournament_id, match, status, started_at, finished_at) VALUES (15, 5, 'Final', 'finished', datetime('now', '-5 days', '19:17:00'), datetime('now', '-5 days', '19:17:00', '+12 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (16, 'finished', datetime('now', '-10 hours'), datetime('now', '-10 hours', '+8 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (17, 'finished', datetime('now', '-15 hours'), datetime('now', '-15 hours', '+12 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (18, 'finished', datetime('now', '-20 hours'), datetime('now', '-20 hours', '+6 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (19, 'finished', datetime('now', '-25 hours'), datetime('now', '-25 hours', '+14 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (20, 'finished', datetime('now', '-30 hours'), datetime('now', '-30 hours', '+7 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (21, 'finished', datetime('now', '-35 hours'), datetime('now', '-35 hours', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (22, 'finished', datetime('now', '-40 hours'), datetime('now', '-40 hours', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (23, 'finished', datetime('now', '-45 hours'), datetime('now', '-45 hours', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (24, 'finished', datetime('now', '-50 hours'), datetime('now', '-50 hours', '+13 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (25, 'finished', datetime('now', '-55 hours'), datetime('now', '-55 hours', '+8 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (26, 'finished', datetime('now', '-60 hours'), datetime('now', '-60 hours', '+10 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (27, 'finished', datetime('now', '-65 hours'), datetime('now', '-65 hours', '+7 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (28, 'finished', datetime('now', '-70 hours'), datetime('now', '-70 hours', '+14 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (29, 'finished', datetime('now', '-75 hours'), datetime('now', '-75 hours', '+6 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (30, 'finished', datetime('now', '-80 hours'), datetime('now', '-80 hours', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (31, 'finished', datetime('now', '-85 hours'), datetime('now', '-85 hours', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (32, 'finished', datetime('now', '-90 hours'), datetime('now', '-90 hours', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (33, 'finished', datetime('now', '-95 hours'), datetime('now', '-95 hours', '+13 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (34, 'finished', datetime('now', '-100 hours'), datetime('now', '-100 hours', '+8 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (35, 'finished', datetime('now', '-105 hours'), datetime('now', '-105 hours', '+12 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (36, 'finished', datetime('now', '-110 hours'), datetime('now', '-110 hours', '+6 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (37, 'finished', datetime('now', '-115 hours'), datetime('now', '-115 hours', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (38, 'finished', datetime('now', '-120 hours'), datetime('now', '-120 hours', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (39, 'finished', datetime('now', '-125 hours'), datetime('now', '-125 hours', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (40, 'finished', datetime('now', '-130 hours'), datetime('now', '-130 hours', '+13 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (41, 'finished', datetime('now', '-135 hours'), datetime('now', '-135 hours', '+8 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (42, 'finished', datetime('now', '-140 hours'), datetime('now', '-140 hours', '+10 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (43, 'finished', datetime('now', '-145 hours'), datetime('now', '-145 hours', '+7 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (44, 'finished', datetime('now', '-150 hours'), datetime('now', '-150 hours', '+14 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (45, 'finished', datetime('now', '-155 hours'), datetime('now', '-155 hours', '+6 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (46, 'finished', datetime('now', '-160 hours'), datetime('now', '-160 hours', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (47, 'finished', datetime('now', '-165 hours'), datetime('now', '-165 hours', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (48, 'finished', datetime('now', '-170 hours'), datetime('now', '-170 hours', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (49, 'finished', datetime('now', '-175 hours'), datetime('now', '-175 hours', '+13 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (50, 'finished', datetime('now', '-180 hours'), datetime('now', '-180 hours', '+8 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (51, 'finished', datetime('now', '-185 hours'), datetime('now', '-185 hours', '+12 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (52, 'finished', datetime('now', '-190 hours'), datetime('now', '-190 hours', '+6 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (53, 'finished', datetime('now', '-195 hours'), datetime('now', '-195 hours', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (54, 'finished', datetime('now', '-200 hours'), datetime('now', '-200 hours', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (55, 'finished', datetime('now', '-205 hours'), datetime('now', '-205 hours', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (56, 'finished', datetime('now', '-210 hours'), datetime('now', '-210 hours', '+13 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (57, 'finished', datetime('now', '-215 hours'), datetime('now', '-215 hours', '+8 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (58, 'finished', datetime('now', '-220 hours'), datetime('now', '-220 hours', '+10 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (59, 'finished', datetime('now', '-225 hours'), datetime('now', '-225 hours', '+7 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (60, 'finished', datetime('now', '-230 hours'), datetime('now', '-230 hours', '+14 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (61, 'finished', datetime('now', '-235 hours'), datetime('now', '-235 hours', '+6 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (62, 'finished', datetime('now', '-240 hours'), datetime('now', '-240 hours', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (63, 'finished', datetime('now', '-245 hours'), datetime('now', '-245 hours', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (64, 'finished', datetime('now', '-250 hours'), datetime('now', '-250 hours', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (65, 'finished', datetime('now', '-255 hours'), datetime('now', '-255 hours', '+13 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (66, 'finished', datetime('now', '-12 hours'), datetime('now', '-12 hours', '+4 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (67, 'finished', datetime('now', '-18 hours'), datetime('now', '-18 hours', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (68, 'finished', datetime('now', '-24 hours'), datetime('now', '-24 hours', '+14 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (69, 'finished', datetime('now', '-30 hours'), datetime('now', '-30 hours', '+7 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (70, 'finished', datetime('now', '-36 hours'), datetime('now', '-36 hours', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (71, 'finished', datetime('now', '-42 hours'), datetime('now', '-42 hours', '+6 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (72, 'finished', datetime('now', '-48 hours'), datetime('now', '-48 hours', '+13 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (73, 'finished', datetime('now', '-54 hours'), datetime('now', '-54 hours', '+8 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (74, 'finished', datetime('now', '-60 hours'), datetime('now', '-60 hours', '+12 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (75, 'finished', datetime('now', '-66 hours'), datetime('now', '-66 hours', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (76, 'finished', datetime('now', '-72 hours'), datetime('now', '-72 hours', '+10 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (77, 'finished', datetime('now', '-78 hours'), datetime('now', '-78 hours', '+14 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (78, 'finished', datetime('now', '-84 hours'), datetime('now', '-84 hours', '+7 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (79, 'finished', datetime('now', '-90 hours'), datetime('now', '-90 hours', '+11 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (80, 'finished', datetime('now', '-96 hours'), datetime('now', '-96 hours', '+6 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (81, 'finished', datetime('now', '-102 hours'), datetime('now', '-102 hours', '+13 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (82, 'finished', datetime('now', '-108 hours'), datetime('now', '-108 hours', '+8 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (83, 'finished', datetime('now', '-114 hours'), datetime('now', '-114 hours', '+12 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (84, 'finished', datetime('now', '-120 hours'), datetime('now', '-120 hours', '+5 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at, finished_at) VALUES (85, 'finished', datetime('now', '-126 hours'), datetime('now', '-126 hours', '+9 minutes'));
            INSERT OR IGNORE INTO games (id, status, started_at) VALUES (86, 'pending', datetime('now', '-1 hours', '+57 minutes'));
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (1, 1, 2, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (2, 1, 3, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (3, 2, 4, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (4, 2, 5, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (5, 3, 2, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (6, 3, 4, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (7, 4, 1, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (8, 4, 5, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (9, 5, 6, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (10, 5, 7, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (11, 6, 5, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (12, 6, 7, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (13, 7, 3, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (14, 7, 4, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (15, 8, 1, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (16, 8, 7, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (17, 9, 3, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (18, 9, 7, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (19, 10, 2, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (20, 10, 6, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (21, 11, 4, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (22, 11, 5, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (23, 12, 2, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (24, 12, 5, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (25, 13, 1, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (26, 13, 3, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (27, 14, 6, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (28, 14, 7, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (29, 15, 1, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (30, 15, 7, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (31, 16, 1, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (32, 16, 2, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (33, 17, 3, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (34, 17, 4, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (35, 18, 5, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (36, 18, 6, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (37, 19, 7, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (38, 19, 1, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (39, 20, 2, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (40, 20, 3, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (41, 21, 4, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (42, 21, 5, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (43, 22, 6, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (44, 22, 7, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (45, 23, 1, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (46, 23, 3, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (47, 24, 2, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (48, 24, 4, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (49, 25, 5, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (50, 25, 6, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (51, 26, 7, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (52, 26, 1, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (53, 27, 3, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (54, 27, 5, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (55, 28, 2, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (56, 28, 6, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (57, 29, 4, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (58, 29, 7, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (59, 30, 1, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (60, 30, 5, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (61, 31, 6, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (62, 31, 2, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (63, 32, 3, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (64, 32, 7, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (65, 33, 4, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (66, 33, 1, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (67, 34, 5, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (68, 34, 3, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (69, 35, 6, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (70, 35, 7, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (71, 36, 1, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (72, 36, 4, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (73, 37, 2, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (74, 37, 5, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (75, 38, 3, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (76, 38, 6, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (77, 39, 7, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (78, 39, 1, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (79, 40, 4, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (80, 40, 2, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (81, 41, 5, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (82, 41, 6, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (83, 42, 7, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (84, 42, 3, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (85, 43, 1, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (86, 43, 2, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (87, 44, 3, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (88, 44, 4, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (89, 45, 5, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (90, 45, 6, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (91, 46, 7, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (92, 46, 1, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (93, 47, 2, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (94, 47, 3, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (95, 48, 4, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (96, 48, 5, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (97, 49, 6, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (98, 49, 7, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (99, 50, 1, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (100, 50, 5, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (101, 51, 2, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (102, 51, 6, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (103, 52, 3, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (104, 52, 7, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (105, 53, 4, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (106, 53, 1, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (107, 54, 5, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (108, 54, 2, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (109, 55, 6, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (110, 55, 3, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (111, 56, 7, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (112, 56, 4, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (113, 57, 1, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (114, 57, 5, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (115, 58, 2, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (116, 58, 6, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (117, 59, 3, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (118, 59, 7, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (119, 60, 4, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (120, 60, 1, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (121, 61, 5, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (122, 61, 2, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (123, 62, 6, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (124, 62, 3, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (125, 63, 7, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (126, 63, 4, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (127, 64, 1, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (128, 64, 5, 0, 0, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (129, 65, 2, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (130, 65, 6, 0, 1, 'Team B');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (131, 66, 1, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (132, 66, NULL, 1, 0, 'Easy Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (133, 67, 2, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (134, 67, NULL, 1, 0, 'Medium Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (135, 68, 3, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (136, 68, NULL, 1, 1, 'Hard Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (137, 69, 4, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (138, 69, NULL, 1, 0, 'Easy Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (139, 70, 5, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (140, 70, NULL, 1, 1, 'Medium Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (141, 71, 6, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (142, 71, NULL, 1, 0, 'Hard Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (143, 72, 7, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (144, 72, NULL, 1, 0, 'Easy Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (145, 73, 1, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (146, 73, NULL, 1, 1, 'Medium Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (147, 74, 2, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (148, 74, NULL, 1, 0, 'Hard Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (149, 75, 3, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (150, 75, NULL, 1, 0, 'Easy Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (151, 76, 4, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (152, 76, NULL, 1, 1, 'Medium Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (153, 77, 5, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (154, 77, NULL, 1, 0, 'Hard Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (155, 78, 6, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (156, 78, NULL, 1, 0, 'Easy Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (157, 79, 7, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (158, 79, NULL, 1, 1, 'Medium Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (159, 80, 1, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (160, 80, NULL, 1, 1, 'Hard Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (161, 81, 2, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (162, 81, NULL, 1, 0, 'Easy Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (163, 82, 3, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (164, 82, NULL, 1, 1, 'Medium Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (165, 83, 4, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (166, 83, NULL, 1, 0, 'Hard Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (167, 84, 5, 0, 1, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (168, 84, NULL, 1, 0, 'Easy Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (169, 85, 6, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (170, 85, NULL, 1, 1, 'Medium Bot');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (171, 86, 6, 0, 0, 'Team A');
            INSERT OR IGNORE INTO participants (id, game_id, user_id, is_bot, is_winner, team_name) VALUES (172, 86, 2, 0, 0, 'Team B');
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (1, 1, 2, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (2, 1, 3, 'Team B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (3, 2, 4, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (4, 2, 5, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (5, 3, 2, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (6, 3, 4, 'Team B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (7, 4, 1, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (8, 4, 5, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (9, 5, 6, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (10, 5, 7, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (11, 6, 5, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (12, 6, 7, 'Team B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (13, 7, 3, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (14, 7, 4, 'Team B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (15, 8, 1, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (16, 8, 7, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (17, 9, 3, 'Team A', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (18, 9, 7, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (19, 10, 2, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (20, 10, 6, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (21, 11, 4, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (22, 11, 5, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (23, 12, 2, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (24, 12, 5, 'Team B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (25, 13, 1, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (26, 13, 3, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (27, 14, 6, 'Team A', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (28, 14, 7, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (29, 15, 1, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (30, 15, 7, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (31, 16, 1, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (32, 16, 2, 'Team B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (33, 17, 3, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (34, 17, 4, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (35, 18, 5, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (36, 18, 6, 'Team B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (37, 19, 7, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (38, 19, 1, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (39, 20, 2, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (40, 20, 3, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (41, 21, 4, 'Team A', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (42, 21, 5, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (43, 22, 6, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (44, 22, 7, 'Team B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (45, 23, 1, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (46, 23, 3, 'Team B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (47, 24, 2, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (48, 24, 4, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (49, 25, 5, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (50, 25, 6, 'Team B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (51, 26, 7, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (52, 26, 1, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (53, 27, 3, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (54, 27, 5, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (55, 28, 2, 'Team A', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (56, 28, 6, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (57, 29, 4, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (58, 29, 7, 'Team B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (59, 30, 1, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (60, 30, 5, 'Team B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (61, 31, 6, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (62, 31, 2, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (63, 32, 3, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (64, 32, 7, 'Team B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (65, 33, 4, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (66, 33, 1, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (67, 34, 5, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (68, 34, 3, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (69, 35, 6, 'Team A', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (70, 35, 7, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (71, 36, 1, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (72, 36, 4, 'Team B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (73, 37, 2, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (74, 37, 5, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (75, 38, 3, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (76, 38, 6, 'Team B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (77, 39, 7, 'Team A', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (78, 39, 1, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (79, 40, 4, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (80, 40, 2, 'Team B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (81, 41, 5, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (82, 41, 6, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (83, 42, 7, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (84, 42, 3, 'Team B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (85, 43, 1, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (86, 43, 2, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (87, 44, 3, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (88, 44, 4, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (89, 45, 5, 'Team A', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (90, 45, 6, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (91, 46, 7, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (92, 46, 1, 'Team B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (93, 47, 2, 'Team A', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (94, 47, 3, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (95, 48, 4, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (96, 48, 5, 'Team B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (97, 49, 6, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (98, 49, 7, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (99, 50, 1, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (100, 50, 5, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (101, 51, 2, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (102, 51, 6, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (103, 52, 3, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (104, 52, 7, 'Team B', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (105, 53, 4, 'Team A', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (106, 53, 1, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (107, 54, 5, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (108, 54, 2, 'Team B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (109, 55, 6, 'Team A', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (110, 55, 3, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (111, 56, 7, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (112, 56, 4, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (113, 57, 1, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (114, 57, 5, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (115, 58, 2, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (116, 58, 6, 'Team B', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (117, 59, 3, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (118, 59, 7, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (119, 60, 4, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (120, 60, 1, 'Team B', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (121, 61, 5, 'Team A', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (122, 61, 2, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (123, 62, 6, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (124, 62, 3, 'Team B', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (125, 63, 7, 'Team A', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (126, 63, 4, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (127, 64, 1, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (128, 64, 5, 'Team B', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (129, 65, 2, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (130, 65, 6, 'Team B', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (131, 66, 1, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (132, 66, NULL, 'Easy Bot', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (133, 67, 2, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (134, 67, NULL, 'Medium Bot', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (135, 68, 3, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (136, 68, NULL, 'Hard Bot', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (137, 69, 4, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (138, 69, NULL, 'Easy Bot', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (139, 70, 5, 'Team A', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (140, 70, NULL, 'Medium Bot', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (141, 71, 6, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (142, 71, NULL, 'Hard Bot', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (143, 72, 7, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (144, 72, NULL, 'Easy Bot', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (145, 73, 1, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (146, 73, NULL, 'Medium Bot', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (147, 74, 2, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (148, 74, NULL, 'Hard Bot', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (149, 75, 3, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (150, 75, NULL, 'Easy Bot', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (151, 76, 4, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (152, 76, NULL, 'Medium Bot', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (153, 77, 5, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (154, 77, NULL, 'Hard Bot', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (155, 78, 6, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (156, 78, NULL, 'Easy Bot', 0);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (157, 79, 7, 'Team A', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (158, 79, NULL, 'Medium Bot', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (159, 80, 1, 'Team A', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (160, 80, NULL, 'Hard Bot', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (161, 81, 2, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (162, 81, NULL, 'Easy Bot', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (163, 82, 3, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (164, 82, NULL, 'Medium Bot', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (165, 83, 4, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (166, 83, NULL, 'Hard Bot', 4);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (167, 84, 5, 'Team A', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (168, 84, NULL, 'Easy Bot', 2);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (169, 85, 6, 'Team A', 3);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (170, 85, NULL, 'Medium Bot', 5);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (171, 86, 6, 'Team A', 1);
            INSERT OR IGNORE INTO scores (id, game_id, scorer_id, team_name, point_number) VALUES (172, 86, 2, 'Team B', 2);
        `);
        console.log('Base de datos inicializada y tablas creadas (si no existían).');
    } finally {
        await db.close();
    }
}
